#!/usr/bin/env bash
# driver-copilot.sh — GitHub Copilot CLI driver for scripts/sdd
# See specs/refactors/002-copilot-cli-agent-support/spec.md (T5)
#
# Exposes the two entry points scripts/sdd's run_agent seam dispatches to,
# mirroring driver-claude.sh's interface exactly:
#   driver_copilot_available          → 0 if the `copilot` binary is on PATH
#   driver_copilot_run_agent <agent> <mode> <model> <prompt>
#                                     → invokes `copilot -p ...` for the given mode
#
# This file is sourced by scripts/sdd near the top; it relies on $ROOT (repo
# root) plus $AGENTS_SRC_DIR / $AGENTS_DST_DIR / $DENY_LIST_FILE and the
# sync-agents helpers (agent_fm_get, sync_one_agent), all defined further
# down in scripts/sdd. That's safe: sourcing only *registers* this file's
# function bodies, it doesn't call them — by the time any function below
# actually runs (main() has dispatched a command), scripts/sdd has finished
# executing top-to-bottom and every one of those names already exists.
#
# bash 3.2 (macOS default — see model_default's comment in scripts/sdd) has
# no namerefs (`local -n`) and throws "unbound variable" on `"${arr[@]}"`
# under `set -u` for an array that was declared but never appended to
# (verified live: `bash -c 'set -u; a=(); for x in "${a[@]}"; do :; done'`
# fails with "a[@]: unbound variable" on the 3.2 shipped here) — every loop
# below is therefore guarded with a `${#arr[@]} -gt 0` check first, the same
# style already used in scripts/sdd's sync_claude_settings_deny (T10).

# Binary-presence check only (D6), same contract as driver_claude_available.
driver_copilot_available() {
  command -v copilot >/dev/null 2>&1
}

###############################################################################
# --allow-tool per mode (§3's table; D4)
###############################################################################
# Measured live against Copilot CLI 1.0.83: under `-p`, tool use is
# auto-approved, so `--allow-tool` grants but does not restrict (§3) — it is
# still passed for every mode, as documentation of intent, matching the table.
# `implement` (mode "full") uses the explicit list `read,search,edit,write,shell`
# — never `--allow-all-tools` (D4). The controls that actually bind are the
# agent's own `tools:` frontmatter (already generated by sync-agents) and
# `--deny-tool` (see driver_copilot_expand_deny_list below).
driver_copilot_allow_tools() { # <mode>
  case "$1" in
    edit)     echo "read,search,edit,write" ;;
    full)     echo "read,search,edit,write,shell" ;;
    readonly) echo "read,search" ;;
    *)
      echo "driver-copilot: unknown mode '$1'" >&2
      return 1
      ;;
  esac
}

###############################################################################
# Deny-list expansion (D3): scripts/lib/deny-list.txt → --deny-tool
###############################################################################
# Populates one global (no namerefs on bash 3.2, see header):
#   COPILOT_DENY_TOOL_ARGS — one `--deny-tool` value per expansion.
#
# Every entry shape in deny-list.txt is expressible as a deny. Measured against
# Copilot CLI 1.0.83 on 2026-09-14, each form below blocked a read or command
# that a control run with no deny performed successfully:
#   read(*.jks)  and  read(**/*.jks)   → both blocked ./probe-temp.jks in the
#                                        repo root, over two consecutive runs,
#                                        while the control returned its
#                                        contents verbatim
#   read(local.properties)             → blocked
#   shell(git:*)  and
#   shell(git push --force:*)          → both blocked `git push --force
#                                        --dry-run`, while the control ran
#
# This supersedes an earlier reading, recorded in this file's first draft and
# in the GitHub docs, that read()/write() match only literal trailing path
# components and that wildcards work for shell() and url() alone. On 1.0.83
# they work for path denies too, and `**/` matches zero directories, so one
# `**/`-prefixed pattern covers an entry at the repo root and nested alike.
#
# Two consequences, both deliberate:
#   - nothing is resolved by globbing the filesystem at dispatch time, so a
#     matching file created *after* the run starts is still covered. The
#     earlier draft enumerated matches with `find`, which left exactly that
#     hole.
#   - no --add-dir is emitted. It only ever ADDS reachable paths beyond the
#     default (cwd and its subdirectories); it has no narrowing mode, and the
#     driver must run with cwd=$ROOT for CLAUDE.md discovery, git and gradle.
#     Passing --add-dir "$ROOT" would have been a no-op dressed as a control.
driver_copilot_expand_deny_list() {
  COPILOT_DENY_TOOL_ARGS=()
  [ -f "$DENY_LIST_FILE" ] || { echo "driver-copilot: $DENY_LIST_FILE not found" >&2; return 1; }

  local line
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [ -z "$line" ] && continue
    case "$line" in
      "#"*) continue ;;
      *" "*)
        # multi-word → a shell command deny; ':*' makes it a prefix match, so
        # "git push --force origin main" is caught, not only the bare command.
        COPILOT_DENY_TOOL_ARGS+=("shell(${line}:*)")
        ;;
      *)
        # single word, glob or not → a path deny on both read and write
        COPILOT_DENY_TOOL_ARGS+=("read(**/${line})")
        COPILOT_DENY_TOOL_ARGS+=("write(**/${line})")
        ;;
    esac
  done < "$DENY_LIST_FILE"
  return 0
}

###############################################################################
# Drift warning (D7): .claude/agents/*.md vs .github/agents/*.agent.md
###############################################################################
# Prints a warning naming every file that `sdd sync-agents` would regenerate
# differently from what's currently on disk, then always returns 0 — it never
# blocks dispatch and never regenerates (a silent rewrite mid-`implement`
# would mix generated output into a task's diff, per D7's answer). Reuses the
# real generator (sync_one_agent/agent_fm_get, scripts/sdd, T7) against a
# scratch directory so this is a byte-for-byte comparison against what the
# generator would actually produce today, not a second implementation that
# could itself drift from it.
driver_copilot_warn_drift() {
  [ -d "$AGENTS_SRC_DIR" ] || return 0
  local tmp_dir src name stale=()
  tmp_dir="$(mktemp -d)"
  for src in "$AGENTS_SRC_DIR"/*.md; do
    [ -f "$src" ] || continue
    name="$(agent_fm_get "$src" name)"
    [ -n "$name" ] || continue
    sync_one_agent "$src" "$tmp_dir" >/dev/null 2>&1 || continue
    if ! diff -q "$tmp_dir/$name.agent.md" "$AGENTS_DST_DIR/$name.agent.md" >/dev/null 2>&1; then
      stale+=("${AGENTS_DST_DIR#"$ROOT"/}/$name.agent.md")
    fi
  done
  rm -rf "$tmp_dir"
  if [ "${#stale[@]}" -gt 0 ]; then
    echo "Warning: .github/agents/ is stale relative to .claude/agents/ — run './scripts/sdd sync-agents' to regenerate. Running anyway (D7); stale file(s):" >&2
    printf '  · %s\n' "${stale[@]}" >&2
  fi
  return 0
}

###############################################################################
# Dispatch
###############################################################################

# Usage: driver_copilot_run_agent <agent> <mode> <model> <prompt>
#   <agent>: passed to `--agent <agent>` (Copilot's custom-agent dispatch —
#            same short names as Claude's subagent naming: sdd-align,
#            sdd-implement, sdd-verify, kotlin-ktlint).
#   <mode>: edit      → --allow-tool 'read,search,edit,write'
#           full      → --allow-tool 'read,search,edit,write,shell' (the
#             `implement` path; D4 — an explicit list, never --allow-all-tools)
#           readonly  → --allow-tool 'read,search' --deny-tool 'write,shell'
#             plus `-s --log-level none` for clean stdout (verdict parsing);
#             also tees combined stdout/stderr into $RUN_AGENT_OUTPUT, same
#             contract as driver-claude.sh's readonly branch.
#   Every mode gets the deny-list.txt expansion (D3) and a pre-dispatch drift
#   warning (D7) first.
driver_copilot_run_agent() {
  local agent="$1" mode="$2" model="$3" prompt="$4"
  local allow_tools
  allow_tools="$(driver_copilot_allow_tools "$mode")" || return 1

  driver_copilot_warn_drift
  driver_copilot_expand_deny_list || return 1

  # --no-ask-user: without it the agent can call ask_user and block forever on
  # a run with no terminal attached.
  local cmd=(copilot -p "$prompt" --agent "$agent" --model "$model" \
             --allow-tool "$allow_tools" --no-ask-user)
  local d
  if [ "${#COPILOT_DENY_TOOL_ARGS[@]}" -gt 0 ]; then
    for d in "${COPILOT_DENY_TOOL_ARGS[@]}"; do
      cmd+=(--deny-tool "$d")
    done
  fi

  case "$mode" in
    edit)
      ( cd "$ROOT" && "${cmd[@]}" ) || true
      ;;
    full)
      ( cd "$ROOT" && "${cmd[@]}" ) || true
      ;;
    readonly)
      cmd+=(--deny-tool "write,shell" -s --log-level none)
      RUN_AGENT_OUTPUT="$(mktemp)"
      # Deliberately no `|| true` here (mirrors driver-claude.sh's readonly
      # branch and the bug T4 fixed there): cmd_verify (D5) needs the real
      # exit status of the `copilot` invocation to tell an infrastructure
      # failure apart from a completed run with an unparseable verdict.
      # `set -o pipefail` (scripts/sdd, sourced into this file) makes the
      # pipeline's status the `copilot` process's status even through `tee`.
      ( cd "$ROOT" && "${cmd[@]}" ) 2>&1 | tee "$RUN_AGENT_OUTPUT"
      ;;
    *)
      echo "driver-copilot: unknown mode '$mode'" >&2
      return 1
      ;;
  esac
}
